### ISSUE TITLE
Make profile and header photos for facebook and twitter using new logo.

### ISSUE THREAD

**Issue by siakaramalegos** [siakaramalegos/clioandcalliope#27]

**Comment by glynnis** [comment]
Got the dimensions for these from an article, but I don't actually have a Facebook page where I could experiment with these. It sounds like they ask you to upload one version for desktop, and one for mobile?

If the chevron shape at the bottom seems weird on Facebook, I can easily take it out for the social media images.

Let me know what you think of these:

Facebook desktop:
![facebook_mobile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5408895b2805d50200f6b379/125516c66e82c728ace21e0d46ee959926808ca684d6b24ca654fc916b0a65633b0ba92e7391a172fd1722070d5d1da4435d0e44aafd8d2ba6b134268a5a0bbf827f4366846c4ff8e7df46f554f832815d84b1b68b49c1e83d2ce1838b4f3e190c0ac4.png)

Facebook mobile:
![facebook.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5408895b2805d50200f6b379/125516c66e82c728ace21e0d46ee959926808ca684abf301b44fff9e2c4533317346f6727687b12be7102e005f094aa84158584caaf98f2bf4e52e6c981e5ab38532022d8c6853beb2901eb80bbb258a4f85bfba8248c0e83a27f5c6.png)

If you like them I'll send you the files over Slack, since I think GitHub might compress them here.

**Comment by glynnis** [comment]
For reference, these are Facebook dimensions:
828 px wide by 315 px on desktop
640 px wide by 360 px tall on mobile

For Twitter:
1500px x 500px

**Comment by glynnis** [comment]
Something more like this?

![facebook_mobile_1](https://user-images.githubusercontent.com/1529366/32525714-6dfae096-c3eb-11e7-8456-a09391018694.png)
![facebook_desktop_1](https://user-images.githubusercontent.com/1529366/32525715-6e1d0950-c3eb-11e7-967d-298a166a8312.png)

With the color logo on white as the profile photo?

**Comment by glynnis** [comment]
These have all been uploaded to the appropriate platforms, and files are in Google Drive.
